version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:1.19
    depends_on:
      - php
    ports:
      - "80:80" 
    volumes:
      - ./backend:/app
      - ./docker/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - devnet
    
  php:
    container_name: php
    image: php:7.4-fpm
    volumes:
      - ./backend:/var/www/html/
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - devnet
  
  node:
    container_name: node
    image: node:14   
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=dev
    command: bash -c "yarn run serve"
    networks:
      - devnet
    
networks:
  devnet:
    driver: bridge